ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  mask_random_circular_shift: false
  force_masking_even_with_zero_weight: false
  separate_head: true
  head_norm_last_layer: false
  head_nlayers: 3
  head_hidden_dim: 2048
student:
  arch: convnext_small
  patch_size: 16
  drop_path_rate: 0.0
  block_chunks: 4
optim:
  epochs: 500
  clip_grad: 3.0
  layerwise_decay: 1.0
schedules:
  lr:
    start: 1e-6
    peak: 2e-4
    end: 1e-6
    warmup_epochs: 80
    freeze_last_layer_epochs: 1
  weight_decay:
    start: 0.04
    end: 0.2
    peak: 0.2
    warmup_epochs: 500
  teacher_temp:
    start: 0.04
    peak: 0.07
    end: 0.07
    warmup_epochs: 120
  momentum:
    start: 0.994
    peak: 1.0
    end: 1.0
    warmup_epochs: 500
